# Generated by Django 5.2.8 on 2026-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('renter', 'Renter'), ('owner', 'Owner')], max_length=20)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
